### ISSUE TITLE
create a new file just for the LOFI playlists

### ISSUE THREAD

**Issue by bhargav794** [bhargav794/hacktoberfest-practice-music-playlists#17]
right now people can add songs and playlists to different files but It'd be much better if LOFI playlists and music are divided separately currently there is only one LOFI playlist in the playlists.md

**Comment by ritesh-karankal** [comment]
Can I make the file?
 or if any other beginner wants then they can do this.
I can provide some of Lofi playlists to them.

**Comment by bhargav794** [comment]
hey @ritesh-karankal, you can work on it.
