### ISSUE TITLE
Lets build the website together.

### ISSUE THREAD

**Issue by akshitarora921** [bhargav794/hacktoberfest-practice-music-playlists#23]

**Comment by bhargav794** [comment]
Hi @akshitarora921 thanks for your concern on this project.The thing is I've started working on the website but the reason I didn't upload it to github is that it is not in position to encourage further contributions and I also has university exams going on so I am trying to balance between the two. I'll upload the basic version of the website by this weekend
Thank you

**Comment by akshitarora921** [comment]
No problem, All the best for exams 👍🏻
